import { HStack, Heading, Spacer, Link, Button, Stack } from "@chakra-ui/react";
import { AllFilters, Filters } from "config/filters";
import { MainLayout } from "layout";
import Head from "next/head";
import React from "react";
import { Project } from "types/projects";
import ProjectDisplayCard from "./ProjectDisplayCard";
interface IHomePageProps {
  projects: Project[];
  filter: Filters;
}
function HomePage({ projects, filter }: IHomePageProps) {
  return (
    <MainLayout>
      <Head>
        <title>Project Gram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HStack>
        <Heading>{`${filter} Projects`}</Heading>
        <Spacer />
        {AllFilters.filter((a) => a != filter).map((filteredFilters) => (
          <Link
            href={
              filteredFilters.toLowerCase() === "top"
                ? "/"
                : filteredFilters.toLowerCase()
            }
            key={filteredFilters}
            passHref
          >
            <Button variant="ghost">{filteredFilters}</Button>
          </Link>
        ))}
      </HStack>
      <Stack mt={10}>
        {projects.map((project) => (
          <ProjectDisplayCard key={project.slug} project={project} />
        ))}
      </Stack>
    </MainLayout>
  );
}

export default HomePage;
